### PR TITLE
added TXT Parser

### PR DESCRIPTION
**Pull request by Totto16**
* I added support for the TXT sentence formatter (according to [this](https://www.plaisance-pratique.com/IMG/pdf/NMEA0183-2.pdf))
* It supports multi and single sentences (see test cases)
* I added tests for it. (fixed a test while adding new ones)

* I also added more to just counting the errors, every error (also thrown Errors) are added to the `errorDescriptions`array, so you can see, which error occured

### CODE REVIEW

**Comment by Totto16** [comment]
Any reason why this was closed  👀

**Comment by infusion** [comment]
Oops, it was closed automatically, since I renamed the master branch to main. This wasn't intentionally

**Comment by Totto16** [comment]
No worries, I love it, when github auto closes things without stating it, and also, this PR needs some work, I'll eventually make it again, but since you changed a few things, it needs a rebase 👍🏼

**Comment by infusion** [comment]
Thanks for your work! I finally had time to modernize all of my npm modules, including this. Having a TXT parser would be very cool!

**Pull request closed without merging**
